name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Test
    runs-on: macos-11
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
        working-directory: ./src
      - name: Run Test
        run: npm test
        working-directory: ./src
      - name: Upload Coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}