name: Jest_test
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Test
    outputs:
      NOTICE_SLACK: ${{ steps.notice-slack.outputs.NOTICE_SLACK }}

    runs-on: macos-11
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
        working-directory: ./src
      - name: Run Test
        run: |
          chmod 700 ~/.ssh
          npm test
        working-directory: ./src
      - name: Upload Coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  slack:
    runs-on: ubuntu-latest
    needs: test
    if: needs.test.outputs.NOTICE_SLACK == 'true'
    steps:
      - uses: technote-space/workflow-conclusion-action@v1

      - name: Slack Notification Success
        if: env.WORKFLOW_CONCLUSION == 'success'
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: ${{ secrets.SLACK_MY_CHANNEL }}
          SLACK_TITLE: Test was successful
          SLACK_USERNAME: GitHub Action Result Notifier
          SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png

      - name: Slack Notification Failure
        if: env.WORKFLOW_CONCLUSION == 'failure'
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: ${{ secrets.SLACK_MY_CHANNEL }}
          SLACK_TITLE: Test was failed
          SLACK_COLOR: '#d10c20'
          SLACK_USERNAME: GitHub Action Result Notifier
          SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png